name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Executa diariamente à meia-noite
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Baixe o repositório do usuário
      - uses: actions/checkout@v3

      # Gera o gráfico da cobra
      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: nkf-kiefer
