name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Executa diariamente à meia-noite
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # Baixe o repositório
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Gera a animação da cobra
      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: nkf-kiefer

      # Faz o push para o branch "output"
      - name: Push Snake Animation
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: .github/snake
